
import { GoogleGenAI, Modality } from "@google/genai";
import { fileToBase64 } from '../utils/imageUtils';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

export const editImageWithGemini = async (file: File, prompt: string): Promise<string> => {
  const base64Data = await fileToBase64(file);
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Data,
            mimeType: file.type,
          },
        },
        {
          text: prompt,
        },
      ],
    },
    config: {
        responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the API.");
};


export const generateImageWithImagen = async (prompt: string, aspectRatio: string): Promise<string> => {
  const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: aspectRatio as "1:1" | "3:4" | "4:3" | "9:16" | "16:9",
      },
  });

  if (response.generatedImages && response.generatedImages.length > 0) {
    const base64ImageBytes = response.generatedImages[0].image.imageBytes;
    return `data:image/png;base64,${base64ImageBytes}`;
  }

  throw new Error("Image generation failed.");
};


export const generateCaptionWithGemini = async (file: File): Promise<string> => {
  const base64Data = await fileToBase64(file);
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-lite',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Data,
            mimeType: file.type,
          },
        },
        {
          text: 'Describe this image in a short, catchy caption suitable for social media.',
        },
      ],
    },
  });

  return response.text.trim();
};
