
import React, { useState } from 'react';
import { generateImageWithImagen } from '../services/geminiService';
import { downloadImage } from '../utils/imageUtils';
import Spinner from './Spinner';
import { Sparkles, Download, AlertCircle, Loader2 } from 'lucide-react';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [aspectRatio, setAspectRatio] = useState('1:1');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const aspectRatios = ["1:1", "16:9", "9:16", "4:3", "3:4"];
  
  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setIsLoading(true);
    setError(null);
    setGeneratedImage(null);

    try {
      const imageUrl = await generateImageWithImagen(prompt, aspectRatio);
      setGeneratedImage(imageUrl);
    } catch (err) {
      setError('Failed to generate image. Please check your API key or try a different prompt.');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-4 md:p-8 text-white">
      <div className="text-center mb-12">
        <h2 className="text-3xl font-black tracking-tighter uppercase mb-2">AI Image Generator</h2>
        <p className="text-gray-500 max-w-md mx-auto">Transform your ideas into high-fidelity visuals using state-of-the-art AI.</p>
      </div>

      <form onSubmit={handleGenerate} className="space-y-6 mb-12 bg-black border border-gray-800 p-6 rounded-xl">
        <div className="space-y-2">
          <label htmlFor="prompt" className="block text-xs font-bold uppercase tracking-widest text-gray-500">Prompt</label>
          <textarea
            id="prompt"
            rows={3}
            value={prompt}
            onChange={e => setPrompt(e.target.value)}
            className="w-full bg-black border border-gray-800 text-white placeholder-gray-700 text-sm rounded-lg focus:border-white focus:ring-0 p-4 outline-none transition-all"
            placeholder="e.g., A minimalist architectural structure in a desert, monochrome, 8k"
            required
          />
        </div>
        <div className="space-y-2">
           <label htmlFor="aspectRatio" className="block text-xs font-bold uppercase tracking-widest text-gray-500">Aspect Ratio</label>
           <div className="flex flex-wrap gap-2">
            {aspectRatios.map(ar => (
                <button
                    type="button"
                    key={ar}
                    onClick={() => setAspectRatio(ar)}
                    className={`px-4 py-2 text-xs font-bold rounded-md border transition-all duration-200 ${aspectRatio === ar ? 'bg-white text-black border-white' : 'bg-transparent text-gray-500 border-gray-800 hover:border-gray-600'}`}
                >
                    {ar}
                </button>
            ))}
           </div>
        </div>
        <button
          type="submit"
          disabled={isLoading || !prompt.trim()}
          className="w-full flex items-center justify-center gap-2 px-6 py-4 text-sm font-black uppercase tracking-widest text-black bg-white rounded-lg hover:bg-gray-200 disabled:opacity-30 disabled:cursor-not-allowed transition-all"
        >
          {isLoading ? (
            <>
              <Loader2 className="w-5 h-5 animate-spin" />
              <span>Generating Visual...</span>
            </>
          ) : (
            <>
              <Sparkles className="w-5 h-5" />
              <span>Generate Image</span>
            </>
          )}
        </button>
        {isLoading && (
          <p className="text-center text-xs text-gray-500 animate-pulse">
            Our AI is currently painting your vision. This usually takes 5-10 seconds.
          </p>
        )}
      </form>

      {error && (
        <div className="flex items-center justify-center gap-2 text-red-500 bg-red-500/10 p-4 rounded-lg border border-red-500/20 mb-8">
          <AlertCircle className="w-5 h-5" />
          <p className="text-sm font-medium">{error}</p>
        </div>
      )}
      
      {generatedImage && (
        <div className="mt-12 flex flex-col items-center gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="w-full border-t border-gray-800 pt-8 flex flex-col items-center gap-6">
              <h3 className="text-xs font-bold uppercase tracking-widest text-gray-500">Generated Result</h3>
              <div className="bg-black border border-gray-800 p-2 rounded-xl shadow-2xl max-w-full">
                  <img src={generatedImage} alt="Generated by AI" className="max-w-full max-h-[70vh] rounded-lg" />
              </div>
              <button
                  onClick={() => downloadImage(generatedImage, `ai-generated-${prompt.substring(0,20).replace(/\s+/g, '-')}.png`)}
                  className="flex items-center gap-2 px-8 py-3 text-sm font-bold uppercase tracking-widest text-white border border-white rounded-lg hover:bg-white hover:text-black transition-all"
              >
                  <Download className="w-5 h-5" />
                  Download Artwork
              </button>
            </div>
        </div>
      )}
    </div>
  );
};

export default ImageGenerator;
